# fly.toml app configuration file generated for cooped-up on 2023-12-03T14:03:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cooped-up"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
