name: Build project

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run linter for server
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          eslint_dir: server/
          eslint_extensions: ts
          eslint_command_prefix: npm install

      - name: Run linter for web
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          eslint_dir: web/
          eslint_extensions: ts,tsx
          eslint_command_prefix: npm install

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run build with pnpm
        uses: creepinson/pnpm-action@master
        with:
          # Arguments to pass to pnpm as a JSON array
          arguments: '["-r build"]'

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
